### PR TITLE
Ayush version

### PR DESCRIPTION
**Pull request by kady-z**
I have completed my task of making blurred navbar work in Firefox as well as I have made navbar responsive so that it can work in mobile-view.

**Desktop view:**

**Mobile View:**

### CODE REVIEW

**Review by irffanasiff — CHANGES_REQUESTED** [review]
Make a seperate file for javascript code of navbar and import it in Index.js (create that file too) then use index js in index.html. Put the file  file.js (renamte to navbar.js) inside Javascript folder(create it) and do same for CSS and use one HTML file index.html

**Review by kady-z — COMMENTED** [review]
I have made all changes. Please have a look. Thank you!.

**Review by kady-z — COMMENTED** [review]
Please see this. I have made requested changes. Thank you!

**Review by irffanasiff — CHANGES_REQUESTED** [review]
put index.html in root folder not in HTML foldert

**Comment by irffanasiff** [comment]
Thank you @kady-z  for your precious time and contribution to the webpage. Looking forward for more contributions

**Pull request merged**
